2025-08-31 06:14:04.589 error 1 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.DataBaseFactory.getDataBase(DataBaseFactory.java:20)
	at com.frame.system.BaseAction.<clinit>(BaseAction.java:15)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.init(ClassFactory.java:54)
	at gzb.frame.server.http.Handle.<clinit>(Handle.java:31)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:115)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:48)
	at gzb.start.Application.run(Application.java:15)
	at gzb.start.Start.main(Start.java:5)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:04.591 error 1 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.init(ClassFactory.java:54)
	at gzb.frame.server.http.Handle.<clinit>(Handle.java:31)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:115)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:48)
	at gzb.start.Application.run(Application.java:15)
	at gzb.start.Start.main(Start.java:5)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:04.592 error 1 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.init(ClassFactory.java:54)
	at gzb.frame.server.http.Handle.<clinit>(Handle.java:31)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:115)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:48)
	at gzb.start.Application.run(Application.java:15)
	at gzb.start.Start.main(Start.java:5)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 12 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 16 more

2025-08-31 06:14:04.593 error 1 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.DataBaseFactory.getDataBase(DataBaseFactory.java:20)
	at gzb.frame.server.http.Handle.<clinit>(Handle.java:35)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:115)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:48)
	at gzb.start.Application.run(Application.java:15)
	at gzb.start.Start.main(Start.java:5)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:07.625 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:07.626 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:10.655 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:10.655 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:13.679 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:13.679 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:16.702 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:16.703 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:19.729 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:19.730 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:22.757 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:22.758 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:25.780 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:25.781 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:28.801 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:28.801 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:31.828 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:31.829 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:34.848 error 70 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:34.848 error 70 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:40.884 error 1 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.init(ClassFactory.java:54)
	at gzb.frame.server.http.Handle.<clinit>(Handle.java:31)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:115)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:48)
	at gzb.start.Application.run(Application.java:15)
	at gzb.start.Start.main(Start.java:5)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:40.885 error 1 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.init(ClassFactory.java:54)
	at gzb.frame.server.http.Handle.<clinit>(Handle.java:31)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:115)
	at gzb.frame.server.http.TomcatServer.startServer(TomcatServer.java:48)
	at gzb.start.Application.run(Application.java:15)
	at gzb.start.Start.main(Start.java:5)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 12 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 16 more

2025-08-31 06:14:43.920 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:43.920 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:46.947 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:46.947 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:49.972 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:49.972 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:52.994 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:52.995 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:56.019 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:56.020 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:14:59.041 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:14:59.042 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:02.066 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:02.067 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:05.088 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:05.089 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:08.110 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:08.110 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:11.137 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:11.138 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:14.156 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:14.156 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:17.174 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:17.174 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:20.193 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:20.193 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:23.210 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:23.210 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:26.226 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:26.226 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:29.244 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:29.244 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:32.261 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:32.262 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:35.278 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:35.278 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:38.304 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:38.304 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:41.322 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:41.322 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:44.340 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:44.340 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:47.358 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:47.358 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:50.374 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:50.375 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:53.391 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:53.391 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:56.407 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:56.408 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:15:59.425 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:15:59.425 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

2025-08-31 06:16:02.441 error 76 gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:117): java.sql.SQLException: 数据库名称不能为空，连接失败........
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:113)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
 | "数据库：[null]，连接失败........"
2025-08-31 06:16:02.441 error 76 gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:293): "loadFiles" | java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at gzb.frame.factory.ClassFactory.createObject(ClassFactory.java:882)
	at gzb.frame.factory.ClassFactory.loadObject(ClassFactory.java:897)
	at gzb.frame.factory.ClassFactory.loadClassInfo(ClassFactory.java:738)
	at gzb.frame.factory.ClassFactory.loadFiles(ClassFactory.java:289)
	at gzb.frame.factory.ClassFactory.lambda$init$0(ClassFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.sql.SQLException: 数据库连接失败
	at com.frame.Frame.<init>(Frame.java:10)
	at com.frame.dao.impl.SysFileDaoImpl.<init>(SysFileDaoImpl.java:7)
	at com.frame.system.BaseSystemAction.<init>(BaseSystemAction.java:28)
	at com.authorizationSystem.api.SystemAction.<init>(Script_3d9e2e269ab26e4a82eab62d71001d7b.groovy)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 8 more
Caused by: java.sql.SQLException: 数据库连接失败
	at gzb.frame.db.DataBaseMsql.initDataBase(DataBaseMsql.java:118)
	at gzb.frame.db.DataBaseMsql.<init>(DataBaseMsql.java:52)
	at gzb.frame.db.BaseDaoImpl.init(BaseDaoImpl.java:93)
	at com.frame.Frame.<init>(Frame.java:8)
	... 12 more

